# Generated by Django 3.1.7 on 2021-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210301_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Выполнить до'),
        ),
        migrations.AlterField(
            model_name='task',
            name='full_description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Подробное описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='', max_length=200, verbose_name='Задача'),
        ),
    ]
